version: "3"
services:
    skozubot:
        build:
            context: .
            args:
                TOKEN: ${TOKEN}
        container_name: "skozubot"
        volumes:
            - ./../skozulogs:/usr/src/app/logs
