version: "3"
services:
    skozubot:
        build:
            context: .
            args:
                TOKEN: ${TOKEN}
        restart: unless-stopped
        container_name: "skozubot"
        volumes:
            - ~/storage/skozulogs:/usr/src/app/logs
