version: "3"
services:
  skozuredis:
    image: "redis"
    container_name: "skozuredis"
    expose:
      - 6379
  skozubot:
    build: .
    container_name: "skozubot"
    volumes:
      - /usr/src/app/logs
    depends_on:
      - "skozuredis"
    links:
      - skozuredis
    environment:
      - REDIS_URL=redis://skozuredis
