name: Deploy DO

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_CONTAINER: skozubot

jobs:
  build-and-deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    env:
      SSH_USER: deploy
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
          END
      - name: Build and deploy container
        working-directory: ./SkozuBot
        run: DOCKER_HOST=“ssh://$SSH_USER@$SSH_HOST” docker-compose up -d
