name: Deploy DO

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REPO: idrevnii/skozubot/skozu-image
  DOCKER_CONTAINER: skozu-image

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.7.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
  deploy:
    needs: [push_to_registry]
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    env:
      SSH_USER: deploy
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
          END

      - name: Login to the GitHub Packages Docker Registry
        run: ssh deploy "docker login $DOCKER_REGISTRY -u $GITHUB_ACTOR -p $GITHUB_TOKEN"

      - name: Pull latest container
        run: |
          ssh deploy "docker pull $DOCKER_REGISTRY/$DOCKER_REPO:latest"
      - name: Stop deployed container
        continue-on-error: true
        run: |
          ssh deploy "docker stop $DOCKER_CONTAINER"
      - name: Remove deployed container
        continue-on-error: true
        run: |
          ssh deploy "docker rm $DOCKER_CONTAINER"
      - name: Start docker container
        run: |
          ssh deploy "docker run -d --name=$DOCKER_CONTAINER $DOCKER_REGISTRY/$DOCKER_REPO:latest"
      - name: Logout from the GitHub Packages Docker Registry
        run: ssh deploy "docker logout $DOCKER_REGISTRY"
