name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            tag:
                description: tag
                required: true

jobs:
    Build-and-deploy:
        env:
            PROJECT: skozubot
            SSH_USER: deploy
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy by ssh
              uses: appleboy/ssh-action@master
              with:
                  host: $SSH_HOST
                  username: $SSH_USER
                  password: $SSH_PASSWORD
                  script: |
                      rm -rf $PROJECT && git clone https://github.com/idrevnii/$PROJECT
                      cd $PROJECT && docker-compose up -d

            - name: Telegram notification
              uses: yanzay/notify-telegram@v0.1.0
              if: always()
              with:
                  chat: ${{ secrets.NOTIFICATION_CHAT_ID }} # user id or channel name secret
                  token: ${{ secrets.NOTIFICATION_TOKEN }} # token secret
                  status: ${{ job.status }} # do not modify this line
